# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fdda831dbf6ce1aa27e7e754cef1c40960a84d2e799f01f57c4c46023c4ef94e5500d6cef9bfb567d42d482a47810f3ab0d932d3856063f7280a9c518348c194

test:
  secret_key_base: 70ffdc88b273d20d67c7c9dcb20dd6aea7a047e69a44417bfaf795c90a4f1831e9eadf216508c0ca469e5ad6ab4dfe70e054619f53404247a6115248f385d5d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
